# Используем официальный образ Python
FROM python:3.12-slim

# Устанавливаем рабочую директорию
WORKDIR /app/bots

# Копируем dependencies
COPY bots/requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем остальные файлы проекта
COPY bots/ .

# Команда для запуска бота
CMD ["python", "main.py"]