version: '3.8'


services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - ./postgs_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.xakatonDRF
    container_name: django_server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./xakatonDRF:/xakatonDRF
    ports:
      - "8000:8000"
    env_file:
      - ./xakatonDRF/.env
    depends_on:
      - db
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bots
    container_name: telegram_bot
    volumes:
      - ./bots:/app/bots
    env_file:
      - ./bots/.env
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge