FROM python:3.12-slim

WORKDIR /app/xakatonDRF

# Установка зависимостей для psycopg2
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY xakatonDRF/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY xakatonDRF/ .

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]