# Generated by Django 5.2 on 2025-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Names_of_field_work',
            field=models.CharField(max_length=255, verbose_name='Наименование полевых работ'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='Note',
            field=models.CharField(max_length=255, verbose_name='Примечание'),
        ),
    ]
