# Generated by Django 5.2 on 2025-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField()),
                ('Production_site', models.CharField()),
                ('Branch_number', models.CharField()),
            ],
            options={
                'verbose_name': 'Принадлежность отделений и производственных участков (ПУ) к подразделениям',
            },
        ),
    ]
