# Generated by Django 5.2 on 2025-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentproduction',
            name='Branch_number',
            field=models.CharField(max_length=255, verbose_name='Номер филиала'),
        ),
        migrations.AlterField(
            model_name='departmentproduction',
            name='Division',
            field=models.CharField(max_length=255, verbose_name='Наименование подразделения'),
        ),
        migrations.AlterField(
            model_name='departmentproduction',
            name='Production_site',
            field=models.CharField(max_length=255, verbose_name='Наименование производственного участка'),
        ),
    ]
