# Generated by Django 5.2 on 2025-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_cultures', models.CharField()),
            ],
            options={
                'verbose_name': 'Наименование культур',
                'verbose_name_plural': 'Наименование культур',
                'ordering': ['Name_of_cultures'],
            },
        ),
    ]
