# Generated by Django 5.2 on 2025-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='Name_of_cultures',
            field=models.CharField(max_length=255, verbose_name='Наименование культур'),
        ),
    ]
