# Generated by Django 5.2 on 2025-04-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('userid', models.CharField(max_length=255, verbose_name='ID пользователя')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
