# Generated by Django 5.2 on 2025-04-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectionsbottg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='SavesTgMessages',
        ),
    ]
