# Generated by Django 5.2 on 2025-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionsbottg', '0002_rename_messages_savestgmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('userid', models.CharField(max_length=255, verbose_name='ID пользователя')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
