# Generated by Django 5.2 on 2025-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionsbottg', '0003_photomessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveMessagesWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('userid', models.CharField(max_length=255, verbose_name='ID пользователя')),
                ('timestamp', models.DateTimeField(verbose_name='Время отправки')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'СообщенияСWhatsApp',
            },
        ),
        migrations.RenameModel(
            old_name='PhotoMessages',
            new_name='PhotoTgMessages',
        ),
        migrations.AlterModelOptions(
            name='phototgmessages',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'ФотоСТелеграмма'},
        ),
        migrations.AlterModelOptions(
            name='savestgmessages',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'СообщенияСТелеграмма'},
        ),
    ]
